###
POST http://localhost:8000/instructor-api/lo
+Content-Type:application/json

{
    "fullname":"ravi",
    "age":12,
    "email":"charan@gmail.com",
    "phoneno":9704176019,
    "username":"charan",
    "password":"charan"
}


###
GET http://localhost:8000/parent-api/getinfo/ravi

###
PUT http://localhost:8000/instructor-api/attendance
Content-Type:application/json

{
    "usernames":[
        "ravi","ajay"
    ]
}
